import Link from "next/link";
import { CheckCircle2, FileText, ReceiptText, ShieldCheck } from "lucide-react";

const advantages = [
  { title: "Prix négociés exclusifs", text: "Accédez aux tarifs professionnels HT sur les références éligibles dès validation de votre compte.", icon: ShieldCheck },
  { title: "Facturation professionnelle", text: "Recevez automatiquement vos factures PDF conformes après paiement de vos commandes B2B.", icon: ReceiptText },
  { title: "Commande minimum 200€ HT", text: "Un seuil clair pour bénéficier du circuit professionnel Barber Paradise.", icon: FileText },
];
const faqs = [
  { question: "Qui peut s’inscrire ?", answer: "Les barbers, salons de coiffure, écoles, distributeurs et professionnels du secteur coiffure/barbe." },
  { question: "Quel délai de validation ?", answer: "Notre équipe étudie chaque demande sous 24-48h ouvrées." },
  { question: "Comment voir les prix pros ?", answer: "Connectez-vous après validation : les produits éligibles affichent le prix HT pro et le prix public barré." },
];
export default function ProPage() {
  return <main className="min-h-screen bg-[#0b0b0b] text-white"><section className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><p className="text-[11px] font-black uppercase tracking-[0.35em] text-[#ff4a8d]">Barber Paradise Pro</p><h1 className="mt-5 text-5xl font-black uppercase tracking-tight md:text-7xl">L’offre professionnelle Barber Paradise</h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/60">Un espace dédié aux barbers, salons et écoles qui veulent commander leur matériel avec des tarifs HT négociés, une facturation claire et un suivi client professionnel.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/pro/inscription" className="bg-[#ff4a8d] px-7 py-4 text-xs font-black uppercase tracking-[0.2em] text-white hover:bg-[#ff1f70]">Créer mon compte pro</Link><Link href="/connexion" className="border border-white/15 px-7 py-4 text-xs font-black uppercase tracking-[0.2em] text-white/70 hover:border-white hover:text-white">Déjà client ? Connexion</Link></div></div><div className="border border-white/10 bg-[#151515] p-8"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-white/40">Conditions principales</p><ul className="mt-6 space-y-4 text-sm text-white/65"><li className="flex gap-3"><CheckCircle2 className="mt-0.5 text-[#ff4a8d]" size={18} /> Validation manuelle sous 24-48h.</li><li className="flex gap-3"><CheckCircle2 className="mt-0.5 text-[#ff4a8d]" size={18} /> Paiements B2B orientés banque et SEPA selon disponibilité.</li><li className="flex gap-3"><CheckCircle2 className="mt-0.5 text-[#ff4a8d]" size={18} /> Facture PDF disponible dans votre espace client.</li></ul></div></section><section className="mx-auto grid max-w-7xl gap-5 px-6 pb-16 md:grid-cols-3">{advantages.map((item)=>{const Icon=item.icon;return <article key={item.title} className="border border-white/10 bg-[#141414] p-7"><Icon className="text-[#ff4a8d]" /><h2 className="mt-5 text-lg font-black uppercase">{item.title}</h2><p className="mt-3 text-sm leading-7 text-white/55">{item.text}</p></article>;})}</section><section className="mx-auto max-w-4xl px-6 pb-24"><p className="text-[11px] font-black uppercase tracking-[0.35em] text-[#ff4a8d]">FAQ</p><div className="mt-6 divide-y divide-white/10 border border-white/10 bg-[#141414]">{faqs.map((faq)=><div key={faq.question} className="p-6"><h3 className="font-black uppercase tracking-[0.12em]">{faq.question}</h3><p className="mt-2 text-sm leading-7 text-white/55">{faq.answer}</p></div>)}</div></section></main>;
}
