ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "mustResetPassword" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "acceptsEmailMarketing" BOOLEAN NOT NULL DEFAULT false;
